version: "3.8"

services:
  db:
    container_name: db
    build:
      context: mysql
      dockerfile: ./Dockerfile
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./mysql/db-data:/var/lib/mysql
      - ./mysql/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    hostname: db

  user-service:
    container_name: user-service
    build:
      context: .
      dockerfile: ./app/services/user/Dockerfile
    tty: true
    volumes:
      - .:/go/src/app
    ports:
      - 50051:50051
    depends_on:
      - db
  book-service:
    container_name: book-service
    build:
      context: .
      dockerfile: ./services/book/Dockerfile
    tty: true
    volumes:
      - .:/go/src/app
    ports:
      - 50052:50052
    depends_on:
      - db

volumes:
  db-data:
