version: "3.8"

services:
  db:
    build:
      context: db
      dockerfile: ./Dockerfile
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
      - /var/lib/mysql
    ports:
      - 3306:3306
    hostname: db

  user-service:
    build:
      context: .
      dockerfile: ./app/services/user/Dockerfile
    tty: true
    volumes:
      - .:/go/src/app
    ports:
      - 50051:50051
    depends_on:
      - db
