version: "3.8"

services:
  db:
    container_name: db
    build:
      context: db
      dockerfile: ./Dockerfile
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    hostname: db

  book-service:
    container_name: book-service
    build:
      context: .
      dockerfile: ./services/book/Dockerfile
    tty: true
    volumes:
      - .:/go/src/app
    ports:
      - 50052:50052
    depends_on:
      - db

volumes:
  data:
